import { mkdirSync, readdirSync, renameSync, rmSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import {
  backendWarnings,
  buildLedgerIndex,
  counts,
  type IndexCounts,
} from "../index/ledgerIndex.ts";
import { loadMessages } from "./messages.ts";
import { activeClaimOverlaps } from "./overlap.ts";
import { ledgerPaths } from "./paths.ts";
import { loadTasks } from "./records.ts";
import { type CommandResult, okResult } from "./result.ts";
import type { TaskRecord } from "./schema.ts";
import { loadClaims, loadIssues } from "./store.ts";
import { indexById, isActionable, readyTasks } from "./tasks.ts";

let textTempCounter = 0;

/** Atomically write text (Markdown) to a file. */
function writeText(file: string, content: string): void {
  const tmp = `${file}.${process.pid}.${++textTempCounter}.tmp`;
  writeFileSync(tmp, content, "utf8");
  renameSync(tmp, file);
}

const GENERATED_HEADER =
  "<!-- GENERATED by `waystation` — do not edit by hand. Edits are overwritten. -->";

const markdownSpecials = /[\\`*_[\]{}()#+\-.!|<>]/g;

function markdownText(value: string | null | undefined): string {
  return (value ?? "").replace(markdownSpecials, "\\$&");
}

function markdownBlock(value: string | null | undefined): string {
  return (value ?? "")
    .trim()
    .split("\n")
    .map((lineText) => markdownText(lineText))
    .join("\n");
}

function markdownListItem(value: string): string {
  return markdownText(value).replace(/\n/g, "\n  ");
}

/** Rebuild the disposable SQLite index from all canonical record types. */
export async function reindex(root?: string): Promise<CommandResult<IndexCounts>> {
  const paths = ledgerPaths(root);
  const data = {
    tasks: loadTasks(root),
    issues: loadIssues(root),
    claims: loadClaims(root),
    messages: loadMessages(root),
  };
  const db = await buildLedgerIndex(paths.index, data);
  const warnings = backendWarnings(db.backend);
  db.close();
  return okResult(counts(data), warnings);
}

function line(t: TaskRecord): string {
  return `- \`${t.id}\` [p${t.priority}] — ${markdownText(t.title)}`;
}

function overlapLines(root: string): string[] {
  return activeClaimOverlaps(root).map(
    (overlap) => `- \`${overlap.task}\` / \`${overlap.otherTask}\` — ${overlap.reason} (advisory)`,
  );
}

/** STATUS.md content, generated from the ledger. */
export function generateStatus(root?: string): string {
  const projectRoot = ledgerPaths(root).root;
  const tasks = loadTasks(root);
  const ready = readyTasks(tasks);
  const readyIds = new Set(ready.map((t) => t.id));
  const byId = indexById(tasks);

  const inProgress = tasks.filter((t) => t.status === "in_progress");
  const review = tasks.filter((t) => t.status === "review");
  const markedBlocked = tasks.filter((t) => t.status === "blocked");
  const waiting = tasks.filter(
    (t) =>
      !readyIds.has(t.id) &&
      !["done", "wont_do", "in_progress", "review", "blocked"].includes(t.status) &&
      t.dependencies.some((d) => byId.get(d)?.status !== "done"),
  );
  const done = tasks.filter((t) => t.status === "done");
  const wontDo = tasks.filter((t) => t.status === "wont_do");
  const openIssues = loadIssues(root).filter(
    (i) => !["closed", "fixed", "verified", "wont_fix", "duplicate"].includes(i.status),
  );

  const s: string[] = [GENERATED_HEADER, "", "# Waystation Status", ""];
  const section = (title: string, rows: string[]) => {
    s.push(`## ${title}`);
    s.push(rows.length ? rows.join("\n") : "_none_");
    s.push("");
  };
  section("Ready to claim", ready.map(line));
  section("In progress", inProgress.map(line));
  section("Review", review.map(line));
  section("Marked blocked", markedBlocked.map(line));
  section("Waiting (blocked by dependencies)", waiting.map(line));
  section("Done", done.map(line));
  section("Won't do", wontDo.map(line));
  section(
    "Open issues",
    openIssues.map(
      (i) => `- \`${i.id}\` [${markdownText(i.severity ?? "-")}] — ${markdownText(i.title)}`,
    ),
  );
  section("Coordination warnings", overlapLines(projectRoot));
  return `${s.join("\n")}\n`;
}

/** active-work.md content, generated from the ledger. */
export function generateActiveWork(root?: string): string {
  const projectRoot = ledgerPaths(root).root;
  const tasks = loadTasks(root);
  const ready = readyTasks(tasks);
  const inProgress = tasks.filter((t) => t.status === "in_progress");
  const warnings = overlapLines(projectRoot);
  const s: string[] = [GENERATED_HEADER, "", "# Active Work", ""];
  s.push("## In progress");
  s.push(inProgress.length ? inProgress.map(line).join("\n") : "_none_");
  s.push("");
  s.push("## Ready");
  s.push(ready.length ? ready.map(line).join("\n") : "_none_");
  s.push("");
  s.push("## Coordination warnings");
  s.push(warnings.length ? warnings.join("\n") : "_none_");
  s.push("");
  return `${s.join("\n")}\n`;
}

/** blocked.md content: tasks that cannot start because a dependency is unmet. */
export function generateBlocked(root?: string): string {
  const tasks = loadTasks(root);
  const byId = indexById(tasks);
  const blocked = tasks
    .filter((t) => !["done", "wont_do", "in_progress", "review"].includes(t.status))
    .filter((t) => !isActionable(t, byId))
    .map((t) => {
      const unmet = t.dependencies.filter((d) => byId.get(d)?.status !== "done");
      return `- \`${t.id}\` — waiting on: ${unmet.join(", ") || "(marked blocked)"}`;
    });
  const s = [
    GENERATED_HEADER,
    "",
    "# Blocked",
    "",
    blocked.length ? blocked.join("\n") : "_none_",
    "",
  ];
  return `${s.join("\n")}\n`;
}

/** Write STATUS.md + context files from the ledger. Never touches summary.md. */
export function generateReports(root?: string): string[] {
  const paths = ledgerPaths(root);
  mkdirSync(join(paths.ledger, "reports"), { recursive: true });
  mkdirSync(join(paths.ledger, "context"), { recursive: true });
  const written: string[] = [];
  const write = (file: string, content: string) => {
    writeText(file, content);
    written.push(file);
  };
  write(join(paths.ledger, "reports", "STATUS.md"), generateStatus(root));
  write(join(paths.ledger, "context", "active-work.md"), generateActiveWork(root));
  write(join(paths.ledger, "context", "blocked.md"), generateBlocked(root));
  return written;
}

/** One-way JSON->Markdown record views under views/tasks/. */
export function generateTaskViews(root?: string): number {
  const paths = ledgerPaths(root);
  const dir = join(paths.ledger, "views", "tasks");
  mkdirSync(dir, { recursive: true });
  const tasks = loadTasks(root);

  // Prune stale view files no longer backed by a current task (idempotency).
  const current = new Set(tasks.map((t) => `${t.id}.md`));
  try {
    for (const f of readdirSync(dir)) {
      if (f.endsWith(".md") && !current.has(f)) rmSync(join(dir, f));
    }
  } catch {
    // dir may not exist yet; nothing to prune
  }

  for (const t of tasks) {
    const md = [
      GENERATED_HEADER,
      "",
      `# ${markdownText(t.id)} — ${markdownText(t.title)}`,
      `status: ${t.status}  priority: ${t.priority}  scope: ${t.scope ?? "-"}`,
      ...(t.commits.length ? [`commits: ${t.commits.map(markdownText).join(", ")}`] : []),
      "",
      markdownBlock(t.description),
      "",
      "## Acceptance",
      ...t.acceptance.map((a) => `- ${markdownListItem(a)}`),
      "",
    ].join("\n");
    writeText(join(dir, `${t.id}.md`), `${md}\n`);
  }
  return tasks.length;
}
