import { mkdirSync, readdirSync, readFileSync, renameSync, rmSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import {
  backendWarnings,
  buildLedgerIndex,
  counts,
  type IndexCounts,
} from "../index/ledgerIndex.ts";
import { loadMessages } from "./messages.ts";
import { ledgerPaths } from "./paths.ts";
import { loadTasks } from "./records.ts";
import { type CommandResult, okResult } from "./result.ts";
import type { TaskRecord } from "./schema.ts";
import { loadClaims, loadIssues } from "./store.ts";
import { indexById, isActionable, readyTasks } from "./tasks.ts";

/** Atomically write text (Markdown) to a file. */
function writeText(file: string, content: string): void {
  const tmp = `${file}.tmp`;
  writeFileSync(tmp, content, "utf8");
  renameSync(tmp, file);
}

const GENERATED_HEADER =
  "<!-- GENERATED by `waystation` — do not edit by hand. Edits are overwritten. -->";

/** Rebuild the disposable SQLite index from all canonical record types. */
export async function reindex(root?: string): Promise<CommandResult<IndexCounts>> {
  const paths = ledgerPaths(root);
  const data = {
    tasks: loadTasks(root),
    issues: loadIssues(root),
    claims: loadClaims(root),
    messages: loadMessages(root),
  };
  const db = await buildLedgerIndex(paths.index, data);
  const warnings = backendWarnings(db.backend);
  db.close();
  return okResult(counts(data), warnings);
}

interface IssueLite {
  id: string;
  title: string;
  status: string;
  severity: string;
}

function loadIssuesLite(root?: string): IssueLite[] {
  const dir = join(ledgerPaths(root).ledger, "issues");
  let entries: string[];
  try {
    entries = readdirSync(dir);
  } catch {
    return [];
  }
  const out: IssueLite[] = [];
  for (const name of entries) {
    if (!name.endsWith(".json")) continue;
    try {
      const d = JSON.parse(readFileSync(join(dir, name), "utf8")) as IssueLite;
      out.push({ id: d.id, title: d.title, status: d.status, severity: d.severity });
    } catch {
      // skip unreadable issue in generated output
    }
  }
  return out;
}

function line(t: TaskRecord): string {
  return `- \`${t.id}\` [p${t.priority}] — ${t.title}`;
}

/** STATUS.md content, generated from the ledger. */
export function generateStatus(root?: string): string {
  const tasks = loadTasks(root);
  const ready = readyTasks(tasks);
  const readyIds = new Set(ready.map((t) => t.id));
  const byId = indexById(tasks);

  const inProgress = tasks.filter((t) => t.status === "in_progress");
  const review = tasks.filter((t) => t.status === "review");
  const markedBlocked = tasks.filter((t) => t.status === "blocked");
  const waiting = tasks.filter(
    (t) =>
      !readyIds.has(t.id) &&
      !["done", "wont_do", "in_progress", "review", "blocked"].includes(t.status) &&
      t.dependencies.some((d) => byId.get(d)?.status !== "done"),
  );
  const done = tasks.filter((t) => t.status === "done");
  const wontDo = tasks.filter((t) => t.status === "wont_do");
  const openIssues = loadIssuesLite(root).filter(
    (i) => !["closed", "fixed", "verified", "wont_fix", "duplicate"].includes(i.status),
  );

  const s: string[] = [GENERATED_HEADER, "", "# Waystation Status", ""];
  const section = (title: string, rows: string[]) => {
    s.push(`## ${title}`);
    s.push(rows.length ? rows.join("\n") : "_none_");
    s.push("");
  };
  section("Ready to claim", ready.map(line));
  section("In progress", inProgress.map(line));
  section("Review", review.map(line));
  section("Marked blocked", markedBlocked.map(line));
  section("Waiting (blocked by dependencies)", waiting.map(line));
  section("Done", done.map(line));
  section("Won't do", wontDo.map(line));
  section(
    "Open issues",
    openIssues.map((i) => `- \`${i.id}\` [${i.severity}] — ${i.title}`),
  );
  return `${s.join("\n")}\n`;
}

/** active-work.md content, generated from the ledger. */
export function generateActiveWork(root?: string): string {
  const tasks = loadTasks(root);
  const ready = readyTasks(tasks);
  const inProgress = tasks.filter((t) => t.status === "in_progress");
  const s: string[] = [GENERATED_HEADER, "", "# Active Work", ""];
  s.push("## In progress");
  s.push(inProgress.length ? inProgress.map(line).join("\n") : "_none_");
  s.push("");
  s.push("## Ready");
  s.push(ready.length ? ready.map(line).join("\n") : "_none_");
  s.push("");
  return `${s.join("\n")}\n`;
}

/** blocked.md content: tasks that cannot start because a dependency is unmet. */
export function generateBlocked(root?: string): string {
  const tasks = loadTasks(root);
  const byId = indexById(tasks);
  const blocked = tasks
    .filter((t) => !["done", "wont_do", "in_progress", "review"].includes(t.status))
    .filter((t) => !isActionable(t, byId))
    .map((t) => {
      const unmet = t.dependencies.filter((d) => byId.get(d)?.status !== "done");
      return `- \`${t.id}\` — waiting on: ${unmet.join(", ") || "(marked blocked)"}`;
    });
  const s = [
    GENERATED_HEADER,
    "",
    "# Blocked",
    "",
    blocked.length ? blocked.join("\n") : "_none_",
    "",
  ];
  return `${s.join("\n")}\n`;
}

/** Write STATUS.md + context files from the ledger. Never touches summary.md. */
export function generateReports(root?: string): string[] {
  const paths = ledgerPaths(root);
  mkdirSync(join(paths.ledger, "reports"), { recursive: true });
  mkdirSync(join(paths.ledger, "context"), { recursive: true });
  const written: string[] = [];
  const write = (file: string, content: string) => {
    writeText(file, content);
    written.push(file);
  };
  write(join(paths.ledger, "reports", "STATUS.md"), generateStatus(root));
  write(join(paths.ledger, "context", "active-work.md"), generateActiveWork(root));
  write(join(paths.ledger, "context", "blocked.md"), generateBlocked(root));
  return written;
}

/** One-way JSON->Markdown record views under views/tasks/. */
export function generateTaskViews(root?: string): number {
  const paths = ledgerPaths(root);
  const dir = join(paths.ledger, "views", "tasks");
  mkdirSync(dir, { recursive: true });
  const tasks = loadTasks(root);

  // Prune stale view files no longer backed by a current task (idempotency).
  const current = new Set(tasks.map((t) => `${t.id}.md`));
  try {
    for (const f of readdirSync(dir)) {
      if (f.endsWith(".md") && !current.has(f)) rmSync(join(dir, f));
    }
  } catch {
    // dir may not exist yet; nothing to prune
  }

  for (const t of tasks) {
    const md = [
      GENERATED_HEADER,
      "",
      `# ${t.id} — ${t.title}`,
      `status: ${t.status}  priority: ${t.priority}  scope: ${t.scope ?? "-"}`,
      "",
      (t.description ?? "").trim(),
      "",
      "## Acceptance",
      ...t.acceptance.map((a) => `- ${a}`),
      "",
    ].join("\n");
    writeText(join(dir, `${t.id}.md`), `${md}\n`);
  }
  return tasks.length;
}
