import { mkdirSync, readdirSync, renameSync, rmSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import {
  backendWarnings,
  buildLedgerIndex,
  counts,
  type IndexCounts,
} from "../index/ledgerIndex.ts";
import { loadMessages } from "./messages.ts";
import { activeClaimOverlaps } from "./overlap.ts";
import { ledgerPaths } from "./paths.ts";
import { loadTasks } from "./records.ts";
import { type CommandResult, okResult } from "./result.ts";
import type { TaskRecord } from "./schema.ts";
import { loadClaims, loadIssues } from "./store.ts";
import { indexById, readyTasks, taskReadiness } from "./tasks.ts";

let textTempCounter = 0;

/** Atomically write text (Markdown) to a file. */
function writeText(file: string, content: string): void {
  const tmp = `${file}.${process.pid}.${++textTempCounter}.tmp`;
  writeFileSync(tmp, content, "utf8");
  renameSync(tmp, file);
}

const GENERATED_HEADER =
  "<!-- GENERATED by `waystation` — do not edit by hand. Edits are overwritten. -->";

const markdownSpecials = /[\\`*_[\]{}()#+\-.!|<>]/g;

function markdownText(value: string | null | undefined): string {
  return (value ?? "").replace(markdownSpecials, "\\$&");
}

function markdownBlock(value: string | null | undefined): string {
  return (value ?? "")
    .trim()
    .split("\n")
    .map((lineText) => markdownText(lineText))
    .join("\n");
}

function markdownListItem(value: string): string {
  return markdownText(value).replace(/\n/g, "\n  ");
}

/** Normalize generated Markdown to LF line endings and exactly one final LF. */
export function generatedMarkdown(content: string): string {
  return `${content.replace(/\r\n?/g, "\n").replace(/\n+$/g, "")}\n`;
}

function sortedTasks(root?: string): TaskRecord[] {
  return loadTasks(root).sort((left, right) => left.id.localeCompare(right.id));
}

/** Rebuild the disposable SQLite index from all canonical record types. */
export async function reindex(root?: string): Promise<CommandResult<IndexCounts>> {
  const paths = ledgerPaths(root);
  const data = {
    tasks: loadTasks(root),
    issues: loadIssues(root),
    claims: loadClaims(root),
    messages: loadMessages(root),
  };
  const db = await buildLedgerIndex(paths.index, data);
  const warnings = backendWarnings(db.backend);
  db.close();
  return okResult(counts(data), warnings);
}

function line(t: TaskRecord): string {
  return `- \`${t.id}\` [p${t.priority}] — ${markdownText(t.title)}`;
}

function overlapLines(root: string): string[] {
  return activeClaimOverlaps(root)
    .map(
      (overlap) =>
        `- \`${overlap.task}\` / \`${overlap.otherTask}\` — ${overlap.reason} (advisory)`,
    )
    .sort();
}

/** STATUS.md content, generated from the ledger. */
export function generateStatus(root?: string): string {
  const projectRoot = ledgerPaths(root).root;
  const tasks = sortedTasks(root);
  const ready = readyTasks(tasks);
  const byId = indexById(tasks);
  const readiness = new Map(tasks.map((task) => [task.id, taskReadiness(task, byId)]));

  const inProgress = tasks.filter((t) => t.status === "in_progress");
  const review = tasks.filter((t) => t.status === "review");
  const markedBlocked = tasks.filter((t) => t.status === "blocked");
  const waiting = tasks.filter((t) => readiness.get(t.id)?.state === "waiting");
  const backlog = tasks.filter((t) => t.status === "todo");
  const done = tasks.filter((t) => t.status === "done");
  const wontDo = tasks.filter((t) => t.status === "wont_do");
  const openIssues = loadIssues(root)
    .filter((i) => !["closed", "fixed", "verified", "wont_fix", "duplicate"].includes(i.status))
    .sort((left, right) => left.id.localeCompare(right.id));

  const s: string[] = [GENERATED_HEADER, "", "# Waystation Status", ""];
  const section = (title: string, rows: string[]) => {
    s.push(`## ${title}`);
    s.push(rows.length ? rows.join("\n") : "_none_");
    s.push("");
  };
  section("Ready to claim", ready.map(line));
  section("In progress", inProgress.map(line));
  section("Review", review.map(line));
  section("Marked blocked", markedBlocked.map(line));
  section("Waiting (blocked by dependencies)", waiting.map(line));
  section("Backlog (todo)", backlog.map(line));
  section("Done", done.map(line));
  section("Won't do", wontDo.map(line));
  section(
    "Open issues",
    openIssues.map(
      (i) => `- \`${i.id}\` [${markdownText(i.severity ?? "-")}] — ${markdownText(i.title)}`,
    ),
  );
  section("Coordination warnings", overlapLines(projectRoot));
  return generatedMarkdown(s.join("\n"));
}

/** active-work.md content, generated from the ledger. */
export function generateActiveWork(root?: string): string {
  const projectRoot = ledgerPaths(root).root;
  const tasks = sortedTasks(root);
  const ready = readyTasks(tasks);
  const inProgress = tasks.filter((t) => t.status === "in_progress");
  const warnings = overlapLines(projectRoot);
  const s: string[] = [GENERATED_HEADER, "", "# Active Work", ""];
  s.push("## In progress");
  s.push(inProgress.length ? inProgress.map(line).join("\n") : "_none_");
  s.push("");
  s.push("## Ready");
  s.push(ready.length ? ready.map(line).join("\n") : "_none_");
  s.push("");
  s.push("## Coordination warnings");
  s.push(warnings.length ? warnings.join("\n") : "_none_");
  s.push("");
  return generatedMarkdown(s.join("\n"));
}

/** blocked.md content: tasks that cannot start because a dependency is unmet. */
export function generateBlocked(root?: string): string {
  const tasks = sortedTasks(root);
  const byId = indexById(tasks);
  const blocked = tasks
    .map((task) => ({ task, readiness: taskReadiness(task, byId) }))
    .filter(({ task, readiness }) => task.status === "blocked" || readiness.state === "waiting")
    .map((t) => {
      const blockers = t.readiness.state === "waiting" ? t.readiness.blockers : [];
      return `- \`${t.task.id}\` — waiting on: ${blockers.join(", ") || "(marked blocked)"}`;
    });
  const s = [
    GENERATED_HEADER,
    "",
    "# Blocked",
    "",
    blocked.length ? blocked.join("\n") : "_none_",
    "",
  ];
  return generatedMarkdown(s.join("\n"));
}

function generateTaskView(task: TaskRecord, byId: ReadonlyMap<string, TaskRecord>): string {
  const readiness = taskReadiness(task, byId);
  return generatedMarkdown(
    [
      GENERATED_HEADER,
      "",
      `# ${markdownText(task.id)} — ${markdownText(task.title)}`,
      `status: ${task.status}  priority: ${task.priority}  scope: ${task.scope ?? "-"}`,
      `readiness: ${readiness.state}  reason: ${readiness.reason}`,
      ...(readiness.blockers.length
        ? [`readiness_blockers: ${readiness.blockers.map(markdownText).join(", ")}`]
        : []),
      ...(task.commits.length ? [`commits: ${task.commits.map(markdownText).join(", ")}`] : []),
      "",
      markdownBlock(task.description),
      "",
      "## Acceptance",
      ...task.acceptance.map((criterion) => `- ${markdownListItem(criterion)}`),
    ].join("\n"),
  );
}

export interface GeneratedArtifact {
  /** Path relative to `.waystation`, always using forward slashes. */
  relative: string;
  file: string;
  content: string;
  kind: "default" | "task_view";
}

/** Deterministic in-memory output used by both writers and freshness validation. */
export function expectedGeneratedArtifacts(root?: string, views = false): GeneratedArtifact[] {
  const paths = ledgerPaths(root);
  const artifacts: GeneratedArtifact[] = [
    {
      relative: "reports/STATUS.md",
      file: join(paths.ledger, "reports", "STATUS.md"),
      content: generateStatus(root),
      kind: "default",
    },
    {
      relative: "context/active-work.md",
      file: join(paths.ledger, "context", "active-work.md"),
      content: generateActiveWork(root),
      kind: "default",
    },
    {
      relative: "context/blocked.md",
      file: join(paths.ledger, "context", "blocked.md"),
      content: generateBlocked(root),
      kind: "default",
    },
  ];
  if (!views) return artifacts;

  const tasks = sortedTasks(root);
  const byId = indexById(tasks);
  for (const task of tasks) {
    artifacts.push({
      relative: `views/tasks/${task.id}.md`,
      file: join(paths.ledger, "views", "tasks", `${task.id}.md`),
      content: generateTaskView(task, byId),
      kind: "task_view",
    });
  }
  return artifacts;
}

/** Write STATUS.md + context files from the ledger. Never touches summary.md. */
export function generateReports(root?: string): string[] {
  const written: string[] = [];
  for (const artifact of expectedGeneratedArtifacts(root)) {
    mkdirSync(join(artifact.file, ".."), { recursive: true });
    writeText(artifact.file, artifact.content);
    written.push(artifact.file);
  }
  return written;
}

/** One-way JSON->Markdown record views under views/tasks/. */
export function generateTaskViews(root?: string): number {
  const paths = ledgerPaths(root);
  const dir = join(paths.ledger, "views", "tasks");
  mkdirSync(dir, { recursive: true });
  const artifacts = expectedGeneratedArtifacts(root, true).filter(
    (artifact) => artifact.kind === "task_view",
  );

  // Prune stale view files no longer backed by a current task (idempotency).
  const current = new Set(
    artifacts.map((artifact) => artifact.relative.slice(artifact.relative.lastIndexOf("/") + 1)),
  );
  try {
    for (const f of readdirSync(dir)) {
      if (f.endsWith(".md") && !current.has(f)) rmSync(join(dir, f));
    }
  } catch {
    // dir may not exist yet; nothing to prune
  }

  for (const artifact of artifacts) writeText(artifact.file, artifact.content);
  return artifacts.length;
}
